### ISSUE TITLE
boolean expressions always treated as true

### ISSUE THREAD

**Issue by cszawisza** [matthijs/sqlpp11-connector-postgresql#10]
HI!

When reading a boolean value from db, driver always return true:
https://gist.github.com/cszawisza/9d2b09a5feee3e42e0fe 
gives "User exists"
System openSuse 13.2
Postgresql 9.3.6

I don't know what info can be helpful, so if you need something please let me know

**Comment by rbock** [comment]
Does this work?

```C++
assert(not db(select(sqlpp::value(false).as(sqlpp::alias::a))).front().a);
```

The query translates to `SELECT 0 AS a`. The returned value is interpreted as a bool then.

I seem to remember that Postgresql sometimes yields 't'/'f' for true/false. Maybe that is a configuration parameter for the client?

**Comment by matthijs** [comment]
See the following:

```
postgres=# select exists (select 1);
 ?column?
----------
 t
(1 row)

postgres=# select pg_typeof(exists (select 1));
 pg_typeof
-----------
 boolean
(1 row)
```

@cszawisza: May I use your gist as a testcase ?

**Comment by cszawisza** [comment]
@matthijs You can use it, if it's helpful.

**Comment by cszawisza** [comment]
I fix this issue for me, tests needed.
