### ISSUE TITLE
connection::execute is not implemented

### ISSUE THREAD

**Issue by isliser** [matthijs/sqlpp11-connector-postgresql#16]
Missing implementation of 
`size_t sqlpp::postgresql::connection::execute::execute(const std::string& command);`

**Comment by cszawisza** [comment]
Please try my fork I've recently manage to implement returning feature for insert and update and also better exception handle then the standard lib

https://github.com/cszawisza/sqlpp11-connector-postgresql/tree/develop 

It's working with develop branch of sqlpp

**Comment by isliser** [comment]
Hello cszawisza!
I'll try it. Do you think of pulling changes into the trunk?

**Comment by cszawisza** [comment]
After I manage to fix all issues that I found during implementation, that where 'harmless' for my needs at the moment (e.g. leak of 'allof(tab)' in returning )
