### ISSUE TITLE
incorporate changes from fork @cszawisza

### ISSUE THREAD

**Issue by matthijs** [matthijs/sqlpp11-connector-postgresql#19]
Hi,

I'm not sure how to contact you through github, but your repo doesn't have an issues tab so I'll try to contact you by using this issue report @cszawisza .

May I incorporate your changes in the fork you created in this repository? Of course I'll put you in the copyright notice so that it is obvious that you helped with this library.

Regards, Matthijs

**Comment by cszawisza** [comment]
Yes :) please ask me via b.w at linux.pl if you want some support for the code I write.

**Comment by matthijs** [comment]
Well, thank you at first, but 'ask me via b.w. at linux.pl', what does b.w mean in this case? When I visit linux.pl, well it's a nice polish website, but I'm from the netherlands...

**Comment by cszawisza** [comment]
at -> @ its an email address :)
