### ISSUE TITLE
Better failure return types

### ISSUE THREAD

**Issue by rbock** [matthijs/sqlpp11-connector-postgresql#20]
Hi Matthijs,

MSVC users had a hard time debugging certain sqlpp11 errors, since MSVC did not run into the same static_assert as other compilers. As a result
- I needed to find a better error reporting strategy
- I am giving a talk about this at CppCon and MeetingC++ :-)
- I just pushed a new release of sqlpp11 that is using more differentiated failure return types.

This has a small impact on the connector libraries as well. You should update your code like this:

See https://github.com/rbock/sqlpp11-connector-sqlite3/commit/f2cd30364a96e84d277cef82ae4922883c40a003

Best,

Roland

**Comment by cszawisza** [comment]
Hi.
Fixed :)
