### ISSUE TITLE
Uppercase tablename problem

### ISSUE THREAD

**Issue by more10-sundsvall** [matthijs/sqlpp11-connector-postgresql#27]
The postgres lower case / upper case problem is not handled properly. I have a database with upper case table names. The generated sqlpp datamodel uses the upper case syntax.

terminate called after throwing an instance of 'sqlpp::exception'
  what():  PostgreSQL error: PGRES_FATAL_ERROR: ERROR:  column regref.pk does not exist
LINE 1: SELECT regref.PK,regref.UsrId,regref.FldId,regref.Nr,regref....

So in order to use postgres with sqlpp11 I will need to make all column names lower case in the database, which is not acceptable.

**Comment by MacDue** [comment]
I've had this issue too.

**Comment by matthijs** [comment]
When quering the information_schema database for information about the field it returns the column name lowercased.

The documentation states that identifiers are lowercased automatically: https://www.postgresql.org/docs/11/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
