### ISSUE TITLE
Missing default constructor for connection::connection()

### ISSUE THREAD

**Issue by sergeken** [matthijs/sqlpp11-connector-postgresql#32]
Looks like I forgot to share a change I did in my "old" tree.  The default constructor for connection::connection() is missing.  As such my application fails to compile My version was quite simple.

    connection::connection()
    {
    }

In need a default constructor because my DataClass is default construable without an open session and an explicit open is issued.  This is because I have a single global variable for the Data class.  I tried to include the old code but with all the recent changes I get run time errors after a few SQL statements, which is very odd or maybe because of other changes (date?, the pull request you rejected today) I made in the past.

    class DataStore {
    public:
    //    DataStore() {}
        void
        open (const std::string & name);

        sqlpp::transaction_t<sqlpp::postgresql::connection>
        begin_transaction ();
        static void
        commit_transaction (sqlpp::transaction_t<sqlpp::postgresql::connection> & transaction);
        static void
        rollback_transaction (sqlpp::transaction_t<sqlpp::postgresql::connection> & transaction);

        sqlpp::postgresql::connection db;
    };

**Comment by cszawisza** [comment]
Ok, create a pull request for missing ctor, and create a failing test case for the bug you found, there was a ton of changes that I committed lately, probably one of them generates error at runtime...
