### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by StiventoUser** [matthijs/sqlpp11-connector-postgresql#38]
Hi,
Thanks for the connector. I'm trying to add it to the Conan package manager now.
Can this library be used with the new sqlpp11 version (0.54)?
Also, will you add tags to the project?

**Comment by cszawisza** [comment]
Hi!
I'm using this lib with the newest sqlpp lib with it so I think that it is compatible :)
In following couple of weeks I plan to fix some of the issues with this connector library, then probably I'll add needed tags.
Feel free to submit a PR

**Comment by StiventoUser** [comment]
Ok, sounds great :)
Can I add static build because as I see add_library is now using SHARED?

**Comment by cszawisza** [comment]
Yes, please use BUILD_SHARED_LIBS variable from cmake

**Comment by StiventoUser** [comment]
Could you help me with some questions?
In the last PR was added the adiog's sqlpp11 fork as a submodule and the find_package was commented. Is it the final version? It makes easier to build the project but harder to share the same core.
And the RalfKubis's fork has a lot of changes. Which changes would be used?

**Comment by cszawisza** [comment]
Changes in the master are those that should been used.
If you find a way to clean up / fix the CMake files, please do so.
BTW I'm still wondering that merging the RalfKubis's is a good idea :)

**Comment by StiventoUser** [comment]
Ok, thanks for the help :)
