### ISSUE TITLE
Option enable_tests

### ISSUE THREAD

**Issue by matthijs** [matthijs/sqlpp11-connector-postgresql#39]
Is there a need for 'ENABLE_TESTS'? Why not building the tests anyway?

The tests are only executed when you do a 'make test'.

Regard, Matthijs

**Comment by cszawisza** [comment]
1. this can lead to longer compile times, which can be a bad thing when you only want to install a library.
2. sqlpp lib has it, IMHO would be nice to be compatible

**Comment by matthijs** [comment]
Ok, then I'll keep it in sync with sqlpp11 and enable the tests by default.
