### ISSUE TITLE
Visual Studio support.

### ISSUE THREAD

**Issue by StiventoUser** [matthijs/sqlpp11-connector-postgresql#42]
Hi,
I'm trying to build the library on Windows but there are some errors:
`(e.g include\sqlpp11/postgresql/returning_column_list.h(439): error C3520: 'T': parameter pack must be expanded in this context)`.
Also, there is no appveyor build script to test it.

**Comment by matthijs** [comment]
Thank you for your report, I do not have a windows build environment available. So if someone can step in and try to fix this that would be nice.

Could you at the very least give some more information about your build environment?

And thank you for the notice on the README. I'm going to fix that.

**Comment by StiventoUser** [comment]
I have Win10, Visual Studio 2017, CMake 3.10.1.
But the project is building on VS 2015.
Looks like a bug:
https://github.com/rbock/sqlpp11/issues/140

**Comment by matthijs** [comment]
Is now fixed in the develop branch thanks to merge request #43
