### ISSUE TITLE
AppVeyor failed

### ISSUE THREAD

**Issue by tuket** [matthijs/sqlpp11-connector-postgresql#57]
Hi, AppVeyor has been failing for the last 2 month for MSVC.
Has MSVC support been droped?

**Comment by matthijs** [comment]
No, it is not dropped. But I have no experience with MSVC so I cannot help with that.

If you have any experience it would be nice if you could check out what is going wrong there.

**Comment by matthijs** [comment]
Appveyor works again, see https://ci.appveyor.com/project/matthijs/sqlpp11-connector-postgresql, it now only fails on Visual Studio 2017.

**Comment by gagbo** [comment]
Hopefully this is also fixed by #69
