### ISSUE TITLE
Update to sqlpp 0.30

### ISSUE THREAD

**Issue by rbock** [matthijs/sqlpp11-connector-postgresql#6]
Hi Matthijs,

sqlpp11 0.30 finally got released a few days ago. It requires minor changes in the code generator and you might want to adjust the connection object a bit, too (see for instance tests/MockDb.h). This can help to reduce the amount of template error code when something is done wrong.

The changes should be fairly simple, but that is my biased opinion, of course. If you have questions, please let me know.

Best,

Roland

**Comment by markwright** [comment]
Since I need it right now, I will try to update it and add it to #3 

Thanks, Mark

**Comment by markwright** [comment]
I added my updates for 0.30 to #3

I am unable to test it at the moment though as the application encounters compiler errors with 0.31 when it tries to use tvin on the right hand side of assignments in dynamic_update(), insert_into(), etc.

**Comment by rbock** [comment]
Please open an issue for sqlpp11 regarding those compiler errors.

**Comment by markwright** [comment]
Sure, thanks, I wrote a little testcase rbock/sqlpp11#31

**Comment by matthijs** [comment]
Mark, I merged your pull requests and tested a simple SELECT example on my db and it worked correctly.
