### ISSUE TITLE
Compile for armv7

### ISSUE THREAD

**Issue by talyssoncastro** [matthijs/sqlpp11-connector-postgresql#64]
I'm trying to compile using a docker for armv7 ([https://github.com/dockcross/dockcross](url)) using the command: cmake `-DHinnantDate_ROOT_DIR=/date -DHinnantDate_INCLUDE_DIR=/date/include -DPostgreSQL_LIBRARY=/usr/lib/x86_64-linux-gnu/libpq.so -DPostgreSQL_INCLUDE_DIR=/usr/include/postgresql -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql`
All directories exist on my container, but I got this error message: 

> CMake Error at src/CMakeLists.txt:41 (add_library):
>   Target "sqlpp11-connector-postgresql-dynamic" links to target
>   "HinnantDate::Date" but the target was not found.  Perhaps a find_package()
>   call is missing for an IMPORTED target, or an ALIAS target is missing?
> 
> CMake Error at src/CMakeLists.txt:31 (add_library):
>   Target "sqlpp11-connector-postgresql" links to target "HinnantDate::Date"
>   but the target was not found.  Perhaps a find_package() call is missing for
>   an IMPORTED target, or an ALIAS target is missing?
> 
> CMake Error at tests/CMakeLists.txt:44 (add_executable):
>   Target "sqlpp11-connector-postgresql_tests" links to target
>   "HinnantDate::Date" but the target was not found.  Perhaps a find_package()
>   call is missing for an IMPORTED target, or an ALIAS target is missing?

`cmake` for HinnantDate was successfully executed.
`cmake && make && make install` for sqlpp11 was also successfully executed (I've removed the tests directory because they weren't successfully running).

**Comment by matthijs** [comment]
Sorry for the late response.

Could you please try to install the HinnantDate project using make / make install ? I guess the tests should then work too for sqlpp11 (that's just a guess).

**Comment by matthijs** [comment]
I've tested with dockcross, installing HinnantDate works. After that I've installed sqlpp11 too (without disabling the tests).

When trying to build sqlpp11-connector-postgresql it failed on not having the postgresql libraries available. I have no idea how I can install the PostgreSQL libraries for the cross toolchain.
