### ISSUE TITLE
if schema is public, generated code does not compile

### ISSUE THREAD

**Issue by dgel** [matthijs/sqlpp11-connector-postgresql#68]
`public` is a c++ keyword, so using that for a namespace does not work. Perhaps the schema name could be changed or the script could detect when schema is called public, as that is quite common

**Comment by bromeara** [comment]
is this issue for the ddl2cpp.py script only or is there also an access aspect to it? ie can you correct the issue by editing the generated *.h file without changing the behavior of the header

**Comment by dgel** [comment]
It can be fixed easily by removing the namespace for the schema from the generated headers or renaming the namespace. The only issue is that a namespace is generated with the same name as the schema, but since the schema name is often (and by default) 'public', that doesn't compile

**Comment by bromeara** [comment]
I made the change on a personal branch but I haven't created a pull request yet as I haven't verified all of the behaviors but adding an underscore to this command(as follows) in ddl2cpp.py will allow it to generate schema namespaces that compile that compile. `_writeLine(fd, 0, "namespace " + tableSchema + "_ {")` Its been working for me so far.

**Comment by matthijs** [comment]
@bromeara could you open a pull request? In my opinion this can be added without problems...
