### ISSUE TITLE
How to use it with sqlpp::connection_pool

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [matthijs/sqlpp11-connector-postgresql#76]
Hi!
Seems like you've missed required using or typedef for connection entity in postgresql `connection_config`. Without it I cannot use it with `connection_pool`.

E.g. in `sqlpp11-connector-mysql` it's done: https://github.com/rbock/sqlpp11-connector-mysql/blob/master/include/sqlpp11/mysql/connection_config.h#L39

Thank you!

P.S. The same issue I've met with `sqlpp-connector-sqlite3`.

**Comment by matthijs** [comment]
I thought the connection pooling is work in progress. But let me add the typedef.
