### ISSUE TITLE
Add UUID support

### ISSUE THREAD

**Issue by zamazan4ik** [matthijs/sqlpp11-connector-postgresql#78]
Hi!
Seems like `PostgreSQL` connector doesn't support yet `UUID` type. Is there any easy way to work with `UUID`?
I've found similar discussion here: https://github.com/rbock/sqlpp11/issues/166

**Comment by matthijs** [comment]
Sure, no problem. Which uuid type do you use in c++?

I usually use the variant from boost (https://www.boost.org/doc/libs/1_72_0/libs/uuid/doc/index.html)

I've only some code laying around for the boost variant, but it is easily adaptable to something else.

**Comment by ZaMaZaN4iK** [comment]
I use uuid from Boost. Is it possible to some some generic implementation which will support not only Boost.uuid, but anything else?

However, for me integration with Boost.UUID will be awesome.

Thank you!

**Comment by matthijs** [comment]
I just added the uuid type. You need to adjust the ddl2cpp.py script to detect the type properly (just add 'uuid' to the types map like: 'uuid': 'uuid')

I haven't add any includes to this piece of code so you need to include it prior to your table include.

I leave this issue open because I have a generator laying around for adding more types based on the strong typedef from https://github.com/foonathan/type_safe

**Comment by ZaMaZaN4iK** [comment]
Thank you a lot!

**Comment by ZaMaZaN4iK** [comment]
@matthijs Maybe you have `UUID` implementation for sqlpp (not for your connector)? I want try to use `uuid` type with `sqlpp` but without any success.

**Comment by ZaMaZaN4iK** [comment]
@matthijs Can you make a PR with your `UUID` data type to `sqlpp11` library?

**Comment by matthijs** [comment]
I am not sure if it is useful to add to the sqlpp11 library. Because the UUID type is only supported by PostgreSQL and not by MySQL / Sqlite.

**Comment by matthijs** [comment]
@ZaMaZaN4iK I saw your question about the uuid type in sqlpp11 project.

Do you have any problems with the current implementation?

**Comment by ZaMaZaN4iK** [comment]
No, I have no any problems. But it seems reasonable to have "native" support for uuid data type without including specific headers before table definition :)
