### ISSUE TITLE
Primary key value of the inserted row

### ISSUE THREAD

**Issue by neel** [matthijs/sqlpp11-connector-postgresql#81]
Once a record is inserted it is required to know the id of that inserted record. Preferably the entire record inserted (with default values put in).

**Comment by matthijs** [comment]
Hi,

You can easily do that like:
```c++
model::TabFoo foo;
const auto result = db(sqlpp::postgresql::insert_into(foo).set(foo.gamma = "dsa").returning(foo.c_timepoint));

// or if you have a multi insert
for(const auto& row : db(sqlpp::postgresql::insert_into(foo).set(....).returning(foo.id, foo...))
{
  std::cout << row.id << std::endl;
}
```

Above is a bit of pseudo code, but it will give you an idea on how to use that.

You can try to use all_of(foo) in the returning() but I have to test if that works.

**Comment by neel** [comment]
Hmm. I see. I also needed to include two files. and it only works with `sqlpp::postgresql::insert_into`

```
#include <sqlpp11/postgresql/insert.h>
#include <sqlpp11/postgresql/returning.h>
```

**Comment by neel** [comment]
But This actually is a limitation. Because this query will not be portable with other databases. It may require code change in too many places if database is changed in future.

**Comment by matthijs** [comment]
Then you shouldn't use the specific extension supported in this connector but stick with plain sqlpp11 and use just the connector to have the queries executed on the db.
