### ISSUE TITLE
fix double precision floating point.

### ISSUE THREAD

**Issue by MatthieuTexier** [matthijs/sqlpp11-connector-postgresql#84]
Hi,
The use of std::to_string(double) narrows the value to a fixed precision.
Find attached a patch.
Best regards.
[fp_values.zip](https://github.com/matthijs/sqlpp11-connector-postgresql/files/4781678/fp_values.zip)

**Comment by matthijs** [comment]
Thanks, I'll look into it.

**Comment by MatthieuTexier** [comment]
Check with small values, like 1.e-10
