### ISSUE TITLE
Compilation error when using group by

### ISSUE THREAD

**Issue by neel** [matthijs/sqlpp11-connector-postgresql#85]
I tried to use `count` while performing join using `group by`

    auto records = _connection(
        select(
            reports.id, 
            reports.aoi, 
            reports.toi, 
            reports.roi, 
            reports.story, 
            reports.created, 
            reports.properties,
            reports.author,
            users.firstName, 
            users.lastName,
            count(places.id)
        ).from(
            reports.join(users).on(reports.author == users.id).left_outer_join(places).on(reports.id == places.report)
        ).group_by(reports.id).limit(limit).offset(offset).order_by(reports.id.asc()).unconditionally()
    );
    nlohmann::json spatial_reports = nlohmann::json::array();
    std::size_t last_id;
    for(const auto& record: records){
        // ...
    }
    if(records.size() > 0){
        // ...
    }

It gave me compilation errors.

```
/home/neel/Projects/wee/spatial.cpp:259:29: error: ‘void __for_begin ’ has incomplete type
  259 |     for(const auto& record: records){
      |                             ^~~~~~~
/home/neel/Projects/wee/spatial.cpp:259:29: error: ‘void __for_end ’ has incomplete type
/home/neel/Projects/wee/spatial.cpp:288:16: error: ‘struct sqlpp::assert_no_unknown_aggregates_t’ has no member named ‘size’
```

**Comment by matthijs** [comment]
For postgresql you need to specifiy all columns in the group by statement (except for the aggregate), so it should look like this:
```c++
auto records = _connection(
    select(
        reports.id, 
        reports.aoi, 
        reports.toi, 
        reports.roi, 
        reports.story, 
        reports.created, 
        reports.properties,
        reports.author,
        users.firstName, 
        users.lastName,
        count(places.id)
    ).from(
        reports.join(users).on(reports.author == users.id).left_outer_join(places).on(reports.id == places.report)
    ).group_by(reports.id, reports.aoi, reports.toi, reports.roi, reports.story, reports.created, reports.properties, reports.author, users.firstName, users.Lastname)
     .limit(limit).offset(offset).order_by(reports.id.asc()).unconditionally()
);
```

**Comment by neel** [comment]
But in PgAdmin SQL query works only with group by reports.id.

I tried including all the fields. the `reports.properties` is of type `json` but in sqlpp11 it is mapped as `text`

It gave me exceptions

```
ERROR:  could not identify an equality operator for type json
LINE 1: ...rts.toi,reports.roi,reports.story,reports.created,reports.pr...
                                                             ^
unhandled exception ERROR:  could not identify an equality operator for type json
LINE 1: ...rts.toi,reports.roi,reports.story,reports.created,reports.pr...
                                                             ^
```

**Comment by rbock** [comment]
Interesting. I thought that @matthijs is right, but maybe there are rules for joins that allow this? I´d be thankful if you could dig up the rules that allow to use group by reports.id only.

However, the rules for select in the library are as stated.

Since you apparently cannot group by the JSON field, I see two options:

1. Use `verbatim`. That is a bit hacky, but probably the fastest way.
2. Restructure your query to join with a select. Something like this (taken from test/Select.cpp):

```
  auto rowCount = select(t.alpha, count(t.alpha)).from(t).unconditionally().group_by(t.alpha).as(sqlpp::alias::a);
  db(select(f.omega, rowCount.count)
         .from(f.join(rowCount).on(f.omega == rowCount.alpha))
         .unconditionally()
         .order_by(rowCount.count.asc()));
```
