### ISSUE TITLE
SQLSTATE[42803]: Grouping error

### ISSUE THREAD

**Issue by cszawisza** [matthijs/sqlpp11-connector-postgresql#9]
Hi!
Postgresql forces columns to be in group_by clause or aggregate function when you use it side by side with other aggregate function, so compiling this code
https://gist.github.com/cszawisza/054a94c527cd86afb1a5 should fail, but instead it generates a buggy code, which generates SQLSTATE[42803]: Grouping error

**Comment by rbock** [comment]
Actually, please post this issue for sqlpp11. It should be solved there.

But that is a tough one. It will take some time (I need a vacation first, I guess ;-) )

**Comment by cszawisza** [comment]
Mysql does allow such a construction, so I thought that it should be driver related.
I'll post an issue for sqlpp soon

**Comment by rbock** [comment]
I know, but it is fishy in MySQL, too (it is undefined which row's value is returned).

Thus, I would like to disallow the construct in general and provide a workaround for MySQL that indicates that this is non-standard (that part is easy :-) )

**Comment by cszawisza** [comment]
move to sqlpp lib
