### ISSUE TITLE
Breaking changes in sqlpp11

### ISSUE THREAD

**Issue by rbock** [matthijs/sqlpp11-connector-postgresql#93]
Hi,

In the last few months I updated sqlpp11 in a few ways:

- The connectors for mysql and sqlite3 got moved into the main repo. I wanted to do this for a long time. It makes maintenance easier for me.
- The serializer_t structs got replaced with serialize functions. This will affect `on_conflict`, for instance, but should be easy to replace.
- A few historical constructs (e.g. multi_column, tvin) got dropped.

The code has lived like this on develop for a while now. I would like to merge to master, soon. Ideally, the postgresql connector would be updated to match the changes, too.

If you prefer, we could also move the postgresql connector into the main repo.

WDYT?

Cheers,

Roland

**Comment by Leon0402** [comment]
Moving slpp11 into the main repository could also be a chance to simplify / align the cmake code of the different connectors. Currently postgresql does some things differently: For instance defining seperate targets for static / shared libraries. 

I could help with that.

**Comment by matthijs** [comment]
Yes, I think its a good idea to move this connector into sqlpp11.

Do you have any suggestions how we could arrange that?

**Comment by rbock** [comment]
Regarding static/shared I forgot to mention another major change I made:

The mysql and sqlite3 connector are now header only.

I would prefer to do the same with the postgresql connector. It makes things easier (e.g. installation) and has rather little influence on compile time.

**Comment by rbock** [comment]
I could probably take a stab at it on the weekend.

**Comment by rbock** [comment]
Just pushed https://github.com/rbock/sqlpp11/commit/4c942600bbaf67b0521e7a386b00af8b2ea9764c

Tests are passing for me, but see notes.
Documentations needs to be updated.
CI needs to be updated, too, especially since I am not testing on Windows.

And now might be the time to tackle https://github.com/matthijs/sqlpp11-connector-postgresql/pull/86 and https://github.com/rbock/sqlpp11/issues/392 

Any help would be very much appreciated, of course!

**Comment by rbock** [comment]
Added blob support. That was an interesting exercise :-)

**Comment by rbock** [comment]
Hi,

Hope you are doing fine!

Today I tagged sqlpp11 0.61, which includes the postgresql connector (same as mysql and sqlite3). Thanks for allowing me to integrate the postgresql connector.  And thanks to your diligent work, this was an easy task.

Note: I archived the repositories for the mysql/sqlite3 connectors. It might make sense to do the same for this repo.

Thanks again, stay safe!

Roland

**Comment by matthijs** [comment]
Thanks for including the postgresql connector into the main sqlpp11 library. This makes it for the users hopefully a better experience!

It was a very interesting exercise to learn the sqlpp11 library!

I'll archive this repository as this is not needed anymore.

Stay safe too!

Regards, Matthijs
